x-restart: &restart #тут мы создаем шаблон для использования в ниже описанных контейнерах, чтобы несколько раз не вставлять один и тот же код. называется даный шаблон yaml-якорь.
  restart: always

include: #Данная настройка позволяет прочитать внешний файл, докер-композ прочитает его и добавит в текущую конфигурацию.
  - proxy.yaml

services:
  db: # Название первого сервиса, база данных.
    image: mysql:8 # образ подгрузит с докер хаба
    container_name: docker-ht-db # название контейнера, если не выставим сами, то докер сделает это за нас.
    <<: [*restart] # использование шаблона
    networks: # одно из преимуществ докер-композа - он умеет сам автоматом выирать подсеть из определенного диапозона, назначать ip каждому контейнеру в этой подсети и настраивает DNS опять же внутри этой же сети (благодяря этому контейнеры могут обращаться друг другу по именам сервисов/доменну)
      backend: # в нашем случае по заданию выделена подсеть 172.20.0.0/24 и для каждого сервиса выделена статика.
        ipv4_address: 172.20.0.10 # поэтому нам надо задать их руками.
    environment: # перменные окружения которые будут внутри контейнера, при первом запуске mysql их прочитает и
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # создать пароль рута
      - MYSQL_DATABASE=${MYSQL_DATABASE} # создат БД
      - MYSQL_USER=${MYSQL_USER} # создаст юзера
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} # и пароль к нему
    volumes: # вольюмы нужны для монтирование томов, для сохранения базы вне контейнера, по умолчанию db_data находится /var/lib/docker/volumes/ главная папка докера в линуксе.
      - db_data:/var/lib/mysql # левая часть от двоеточия то что хранится на хосте, а правая часть путь внутри контейнера.
    healthcheck: # проверка доступности
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # пинг внутри контейнера
      interval: 10s # каждые 10 сек докер запускает првоерку
      timeout: 5s # если проверка дольше 5 сек, то считается прваленной
      retries: 3  # кол-во попыток

  web:
    build: # команда на сбор образа на основе написанного мной докерфайла
      context: . # указывает источник файлов для сборки, в данном случае текущая папка
      dockerfile: Dockerfile.python # название докерфайла
    container_name: docker-ht-web
    <<: [*restart]
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment: # переменные для пайтон приложения, чтобы оно могло подключиться к БД
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on: # данная команда указывает порядок запуска, в нашем случае сервис web запуститься только успешной првоерки хелфчека
      db:
        condition: service_healthy

volumes: # тут глобально объявляются все используемые тома
  db_data:

#networks: # а тут глобально использвуемы сети
 # backend: # имя сети 
 #   name: backend # а это как называется сеть в самом докере
 #   driver: bridge  # сетевое подключение типа мост, изолированная сеть для контейнеров на одной машине
 #   ipam: # IP Address Management
 #     config:
  #      - subnet: 172.20.0.0/24 # наша подсеть